# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Only used to deploy to Vercel for previews
  pull_request_target:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: false
        default: 'Just Cause'

jobs:
  build:
    if: github.event_name != 'pull_request_target'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - lib: 'astropy'
            python-version: 3.9
          - lib: 'papyri'
            python-version: 3.9
          - lib: 'IPython'
            python-version: 3.9
          - lib: 'numpy'
            python-version: 3.9
            flags: '--no-narrative --no-exec'
          - lib: 'scipy'
            python-version: 3.9
            flags: '--no-narrative --no-exec'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flit matplotlib 'velin>=0.0.5' tree_sitter coverage pipdeptree 'jinja2<3.1'
        flit install --symlink
        git clone https://github.com/stsewd/tree-sitter-rst
        papyri build-parser
    - name: dependency tree
      run: |
        pipdeptree
    - name: dependency tree (reversed)
      run: |
        pipdeptree -r
    - name: Gen ${{matrix.lib}}
      run: |
        pip install ${{matrix.lib}}
        coverage run -a -m papyri gen examples/${{matrix.lib}}.toml  --no-infer ${{matrix.flags}}
        sleep 1 # time for coverage to write its stuff
        papyri pack
        ls ~/.papyri/data
    - uses: actions/upload-artifact@v3
      with:
        name: doc-bundles
        path: ~/.papyri/data/*.zip
    - name: Convert .coverage sql to xml for upload
      run: |
        coverage report
        coverage xml
        ls -la
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

  ingest:
    if: github.event_name != 'pull_request_target'

    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flit matplotlib 'velin>=0.0.5' pytest-trio tree_sitter coverage 'jinja2<3.1'
        flit install --symlink
        git clone https://github.com/stsewd/tree-sitter-rst
        papyri build-parser
    - uses: actions/download-artifact@v3
      with:
        name: doc-bundles
        path: ~/.papyri/data/

    - name: Misc cli
      run: |
        coverage run -m papyri --help
        ls -al
    - name: Ingest
      run: |
        coverage run -a -m papyri install ~/.papyri/data/*.zip
        coverage run -a -m papyri relink
        coverage run -a -m papyri render --ascii

        # coverage html
        # papyri serve
        ls -al
        # ls -al ~/.papyri/html/p/numpy/

    - name: Test with pytest
      run: |
        pip install scipy
        pytest --cov=papyri --cov-append
        ls -al
    - name: Convert .coverage sql to xml for upload
      run: |
        coverage report
        coverage xml
        ls -la
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

  vercel:
    if: github.event_name == 'pull_request_target'

    runs-on: ubuntu-latest
    needs: [build]
    environment: vercel-deployment
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: doc-bundles
        path: ~/.papyri/data/

    - name: Ingest and Render
      run: |
        papyri ingest  --no-relink ~/.papyri/data/papyri_0.0.8
        papyri ingest  --no-relink ~/.papyri/data/*
        papyri relink
        papyri render

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Deploy Project Artifacts to Vercel
      id: vercel
      working-directory: "/home/runner/.papyri/html"
      run: |
        vercel --version
        vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
        vercel build --token=$VERCEL_TOKEN
        vercel deploy --prebuilt --archive=tgz --token=$VERCEL_TOKEN --meta commit=${{ github.event.pull_request.head.sha }}
        echo "test=world" >> "$GITHUB_OUTPUT"

        vercel ls --token=$VERCEL_TOKEN --meta commit=${{ github.event.pull_request.head.sha }} &> vercel-output
        url=$(cat vercel-output | grep http | awk '{print $2}')
        echo "VERCEL_URL=$url" >> "$GITHUB_OUTPUT"

    - name: Update PR status with Deployment URL
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{ github.token }}
        context: 'Vercel Deployment Preview'
        description: 'Deployed'
        state: 'success'
        target_url: ${{ steps.vercel.outputs.VERCEL_URL }}
        sha: ${{ github.event.pull_request.head.sha || github.sha }}
